### ISSUE TITLE
Code does not work with isotopes 

### ISSUE THREAD

**Issue by tim-degroot** [tomaszborowski/gaussian2xyz#2]
Hi, thanks for the awesome code! I've used it and encountered an issue when using isotopes (such as `H(iso=2)`). Managed to fix this by inserting the following line of code at line 261 of  `extract_geoms_aux.py`:

```python
at_symbol = re.sub(r'\(.*?\)', '', at_symbol) # remove parenthecized nuclear parameters
```

This solution removes any parenthesised nuclear parameters of which there are a lot: [Molecule Specifications | Gaussian.com](https://gaussian.com/molspec/)

tried to make a new branch to open a pull request but wasn't able to so thought I'd share this possible update this way! 

Thanks again for the code which really helps me save a lot of time 👍

**Comment by tomaszborowski** [comment]
Hi Tim, thanks a lot for your feedback and for sharing the solution, I have included it in the code. 
If you find any other bug, please, let me know.

All the best!
Tomasz
